---
# tasks file for photoprism
#

- name: Create Photoprism container
  containers.podman.podman_container:
    name: photoprism
    image: "docker.io/photoprism/photoprism"
    state: started
    volume:
      - "/home/containers/photoprism/originals:/photoprism/originals"
      - "/home/containers/photoprism/import:/photoprism/import"
      - "/home/containers/photoprism/storage:/photoprism/storage"
    ports:
      - "2342:2342"
    security_opt:
      - "seccomp=unconfined"
      - "apparmor=unconfined"
    env:
      PHOTOPRISM_ADMIN_USER: "admin"
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"
      PHOTOPRISM_AUTH_MODE: "public"
      PHOTOPRISM_SITE_URL: "http://photoprism.galaxy.derksencomputing.nl:2342/"
      PHOTOPRISM_ORIGINALS_LIMIT: "100000"
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: "85"
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "false"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "alnitak.galaxy.derksencomputing.nl:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "{{ lookup('community.general.hashi_vault', 'validate_certs=false secret=derksencomputing/data/{{ ansible_fqdn }} token={{ hasicorp_vault_token }} url=https://vault.galaxy.derksencomputing.nl:443')['mariadb_database_photoprism_username_photoprism'] }}"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""

- name: Create systemd unit file for Photoprism container
  containers.podman.podman_generate_systemd:
    name: photoprism
    new: true
    restart_policy: always
    no_header: true
    dest: /home/containers/.config/systemd/user

- name: Ensure Photoprism container is started and enabled
  ansible.builtin.systemd:
    name: container-photoprism
    daemon_reload: true
    state: started
    enabled: true
    scope: user
