---

- name: "Ensure Openntpd package is installed"
  apt:
    name: openntpd
    state: present

- name: "Ensure ntp is enabled and started"
  service:
    name: openntpd
    state: started
    enabled: true

- name: "Ensure openntpd config file"
  template:
    src: templates/ntpd.conf.j2
    dest: /etc/openntpd/ntpd.conf
  notify: restart_openntpd
