---

- name: "Ensure Openntpd is installed"
  pkgng:
    name: openntpd
    state: present

- name: "Ensure ntp is enabled and started"
  service:
    name: openntpd
    state: started
    enabled: true

- name: "Ensure openntpd config file"
  template:
    src: templates/FreeBSD/ntpd.conf.j2
    dest: /usr/local/etc/ntpd.conf
  notify: restart_openntpd
