---

- name: "Ensure ntpd config"
  template:
    src: templates/OpenBSD/ntpd.conf.j2
    dest: /etc/ntpd.conf
  notify:
    - restart_ntpd

- name: "Ensure ntpd is enabled and started"
  service:
    name: ntpd
    enabled: True
    state: started
