#Before executing this role, create the backup repo on the Borgbase website,
#generate a ssh-keypair, and upload the public-key to Borgbase and connect to
#the remote backup-server to store the server's ssh fingerprint. Automating
#these steps with the Borgbase API is on the TODO list. For now this role
#provides a working remote backup solution.

---
# tasks file for backup

- name: "Ensure Borgbackup dependencies are installed"
  pkgng:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - py38-borgbackup

#Initialize the remote Borg archive. If the remote Borg archive already
#exists, the command will exit with return code 2. We will ignore this
#exit code and continue. This task will report changed when the archive
#initialized for the first time.
- name: "Ensure borg backup is initialized"
  shell: "/usr/local/bin/borg init --encryption=repokey-blake2 {{ borgbase_repo }}"
  environment:
    BORG_PASSPHRASE: "{{ borgbase_passphrase }}"
  register: borg_repo_initialized
  changed_when: borg_repo_initialized.rc == 0
  failed_when:
    - borg_repo_initialized.rc != 0
    - borg_repo_initialized.rc != 2

- name: "Ensure Borg repo key is exported"
  shell: "/usr/local/bin/borg key export {{ borgbase_repo }} /root/borg_base_key_export"
  args:
    creates: /root/borg_base_key_export

- name: "Ensure borg_backup Borg wrapper script is available"
  template:
    src: templates/borg_backup
    dest: /usr/local/sbin/borg_backup
    mode: 0700

- name: "Ensure old Borg archives are removed from repo"
  cron:
    name: "Prune old Borg archives"
    minute: "0"
    hour: "1"
    user: root
    job: "/usr/local/sbin/borg_backup prune"
    cron_file: /etc/crontab

- name: "Ensure Daily backup to Borgbase remote repo"
  cron:
    name: "Create daily Borg backup"
    minute: "0"
    hour: "3"
    user: root
    job: "/usr/local/sbin/borg_backup backup"
    cron_file: /etc/crontab
