---

- name: "Ensure kerberos services are present"
  ipa_service:
    name: "{{ item }}/{{ inventory_hostname }}"
    state: present
    ipa_host: vega.galaxy.derksencomputing.nl
    ipa_user: admin
    ipa_pass: "{{ ipa_admin_pass }}"
    validate_certs: False
  with_items: "{{ kerberos_service_principals }}"
  when: kerberos_service_principals is defined
  register: update_kerberos_keytab

- include_tasks: "{{ ansible_os_family }}.yml"
