---

- name: "Ensure IPA client packages are installed"
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - freeipa-client

- name: "Ensure client are enrolled with IPA domain"
  shell: "/usr/sbin/ipa-client-install --unattended --force-join --principal admin --password '{{ ipa_admin_pass }}'"  
  args:
    creates: /etc/ipa/default.conf

- name: "Fetch new Kerberos principals"
  shell: "echo '{{ ipa_admin_pass }}' | /usr/bin/kinit admin && /usr/sbin/ipa-getkeytab -k /etc/krb5.keytab -p '{{ item.item }}/{{ inventory_hostname }}'"
  with_items: 
    - "{{ update_kerberos_keytab.results }}"
  when: update_kerberos_keytab.changed == True

- name: "Check if automount is already configured"
  shell: /bin/grep -q '^ipa_automount_location =.*default.*$' /etc/sssd/sssd.conf
  register: automount_check
  changed_when: False
  ignore_errors: True
  when: 
    - remote_homedir is defined
    - remote_homedir == True

- name: "Ensure remote home directory automount is configured"
  shell: '/usr/sbin/ipa-client-automount --location=default --unattended'
  when: 
    - remote_homedir is defined
    - remote_homedir == True
    - automount_check.failed == True
