---

- name: Add Prometheus systemaccount
  user:
    name: prometheus
    shell: /bin/false
    create_home: False

- name: Download Prometheus archive
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.33.1/prometheus-2.33.1.linux-amd64.tar.gz
    dest: /opt
    mode: '0440'
  register: prometheus_download

- name: Install Prometheus and remove the old installation if necessary
  block: 
  - name: Find all Prometheus archives
    find:
      path: /opt
      patterns: 'prometheus*.tar.gz'
    register: prometheus_archives

  - name: Remove old Prometheus archives
    file:
      path: "{{ item.path }}"
      state: absent
    #Keep the Prometheus archive we just downloaded
    when: item.path != prometheus_download.dest
    loop: "{{ prometheus_archives.files }}"
    loop_control:
      label: "{{ item.path }}"
    
  - name: Remove old prometheus installation directory before installing the new verion
    file:
      dest: /opt/prometheus
      state: absent
  
  - name: Unarchive downloaded Prometheus
    unarchive:
      src: "{{ prometheus_download.dest }}"
      dest: /opt
      remote_src: yes

  - name: Rename extracted Prometheus directory to prometheus
    shell: mv "{{ prometheus_download.dest | regex_replace('\.tar\.gz') }}" prometheus
    args:
      chdir: /opt
      creates: prometheus
    notify: restart_prometheus
  when: 
    - prometheus_download.changed

- name: Create Prometheus configuration directory
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Create Prometheus database storage directory
  file:
    path: /var/prometheus
    state: directory
    mode: '0755'
    owner: prometheus
    group: prometheus

- name: Setup Prometheus configuration file
  template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: restart_prometheus

- name: Setup Prometheus rules file
  template:
    src: templates/rules.yml.j2
    dest: /etc/prometheus/rules.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: restart_prometheus

- name: Setup Prometheus systemd service file
  template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Start and enable Prometheus
  systemd:
    state: started
    name: prometheus
    daemon_reload: yes
    enabled: True

- name: Open TCP port 9090 
  firewalld:
    port: 9090/tcp
    permanent: yes
    state: enabled
  notify: reload_firewalld

- name: Add Alertmanager systemaccount
  user:
    name: alertmanager
    shell: /bin/false
    create_home: False

- name: Download Alertmanager archive
  get_url:
    url: https://github.com/prometheus/alertmanager/releases/download/v0.23.0/alertmanager-0.23.0.linux-amd64.tar.gz
    dest: /opt
    mode: '0440'
  register: alertmanager_download

- name: Install Alertmanager and remove the old installation if necessary
  block: 
  - name: Find all Alertmanager archives
    find:
      path: /opt
      patterns: 'alertmanager*.tar.gz'
    register: alertmanager_archives

  - name: Remove old Alertmanager archives
    file:
      path: "{{ item.path }}"
      state: absent
    #Keep the Alertmanager archive we just downloaded
    when: item.path != alertmanager_download.dest
    loop: "{{ alertmanager_archives.files }}"
    loop_control:
      label: "{{ item.path }}"
    
  - name: Remove old Alertmanager installation directory before installing the new verion
    file:
      dest: /opt/alertmanger
      state: absent
  
  - name: Unarchive downloaded Alertmanager
    unarchive:
      src: "{{ alertmanager_download.dest }}"
      dest: /opt
      remote_src: yes

  - name: Rename extracted Alertmanager directory to Alertmanager
    shell: mv "{{ alertmanager_download.dest | regex_replace('\.tar\.gz') }}" alertmanager
    args:
      chdir: /opt
      creates: alertmanager
    notify: restart_alertmanager
  when: 
    - alertmanager_download.changed

- name: Create Alertmanager configuration directory
  file:
    path: /etc/alertmanager
    state: directory
    mode: '0755'

- name: Create Alertmanager data directory
  file:
    path: /var/alertmanager
    state: directory
    mode: '0755'
    owner: alertmanager
    group: alertmanager

- name: Setup Alertmanager configuration file
  template:
    src: templates/alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: '0644'
  notify: restart_alertmanager

- name: Setup Alertmanager systemd unit file
  template:
    src: templates/alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service

- name: Start and enable Alertmanager
  systemd:
    state: started
    name: alertmanager
    daemon_reload: yes
    enabled: True

- name: Add Grafana repository
  yum_repository:
    name: grafana
    description: Grafana Repository
    file: grafana_repo
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: yes
    gpgkey: https://packages.grafana.com/gpg.key

- name: Install Grafana
  yum:
    name: grafana
    state: present

- name: Start and enable Grafana server
  service:
    state: started
    name: grafana-server
    enabled: True

- name: Open TCP port 3000 
  firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled
  notify: reload_firewalld
