---

- name: Add Prometheus systemaccount
  user:
    name: prometheus
    shell: /bin/false
    create_home: False

- name: Create Prometheus configuration directory
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Create Prometheus configuration directory
  file:
    path: /var/lib/prometheus
    state: directory
    mode: '0755'
    owner: prometheus
    group: prometheus

- name: Download Prometheus archive
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.20.1/prometheus-2.20.1.linux-amd64.tar.gz
    dest: /root
    mode: '0440'

- name: Unarchive Promethues
  unarchive:
    src: /root/prometheus-2.20.1.linux-amd64.tar.gz
    dest: /root
    remote_src: yes

- name: Copy Prometheus binaries to correct path
  copy:
    src: "/root/prometheus-2.20.1.linux-amd64/{{ item }}"
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
  with_items:
    - prometheus
    - promtool

- name: Setup Prometheus configuration file
  template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: restart_prometheus

- name: Setup Prometheus configuration file
  template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Start and enable Prometheus
  systemd:
    state: started
    name: prometheus
    daemon_reload: yes
    enabled: true

- name: Open TCP port 9090 
  firewalld:
    port: 9090/tcp
    permanent: yes
    state: enabled
  notify: reload_firewalld

- name: Add Grafana repository
  yum_repository:
    name: grafana
    description: Grafana Repository
    file: grafana_repo
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: yes
    gpgkey: /etc/pki/tls/certs/ca-bundle.crt

- name: Install Grafana
  yum:
    name: grafana
    state: present

- name: Start and enable Grafana server
  service:
    state: started
    name: grafana-server
    enabled: true

- name: Open TCP port 3000 
  firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled
  notify: reload_firewalld
