---
# tasks file for nfs

#There is no daemon enable command on FreeBSD to enable daemons to start at boot time. I don't
#want to use the template module to template a core system file for a specific nfs daemon. We
#might override some settings if we use the template engine from a different role. I can't use
#the service modele enable function either. There is no way to enable nfs version 4 that way.
- name: "Ensure nfsd version 4 is enabled"
  blockinfile:
    path: /etc/rc.conf
    block: |
      rpcbind_enable="YES"
      nfs_server_enable="YES"
      mountd_flags="-r"
      nfsv4_server_enable="YES"
      gssd_enable="YES"
      gssd_flags="-h"

- name: "Ensure nfsd is restricted to nfs protocol version 4"
  sysctl:
    name: "vfs.nfsd.server_min_nfsvers"
    value: "4"
    sysctl_set: yes

- name: "Ensure exported directories exists"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ nfs_exports }}"

- name: "Ensure exports file exists"
  template:
    src: templates/exports.j2
    dest: /etc/exports
  notify: reload_mountd

- name: "Ensure nfs daemon is started and enabled at boot time"
  service:
    name: nfsd
    state: started
