---
# tasks file for dhcp

- name: Ensure the dhcpd configuration
  template:
    src: ../templates/dhcpd.conf.j2
    dest: /etc/dhcpd.conf
  notify: restart_dhcpd

- name: Ensure dhcpd is enabled to start at boot and is stared
  service:
    name: dhcpd
    enabled: true
    state: started
