---

- name: Ensure syslog message are forwarded to the central logserver
  template:
    src: templates/FreeBSD/forward_syslog.conf.j2
    dest: /etc/syslog.d/forward_syslog.conf
  notify:
    restart_syslog
