---
# tasks file for home_automation

- name: Setup Home Assistant
  debug:
    msg: "Ansible playbook for setting up home assistant"

- name: Ensure the Home Assistant user
  user:
    name: homeassistant
    comment: Home Assistant
    home: /opt/homeassistant
    shell: /bin/bash

- name: Ensure home assistant home directory
  file:
    path: /opt/homeassistant
    state: directory
    mode: '0755'
    owner: homeassistant

- name: Ensure home assistant python venv directory
  file:
    path: /opt/homeassistant/venv
    state: directory
    mode: '0755'
    owner: homeassistant
    group: homeassistant

- name: Install the yum development tools group 
  yum:
    name: 
      - gcc
      - gcc-c++ 
      - systemd-devel
      - python39
      - python39-devel
      - python3-virtualenv
    state: present

- name: Install home assistant as the homeassistant user
  block:
    - name: Python pip install homeassistant in virtualenv
      pip:
        name: homeassistant
        virtualenv: "/opt/homeassistant/venv"
        virtualenv_python: /usr/bin/python3.9
  become_user: homeassistant

- name: Create the homeassistant configuration directory
  file:
    path: /etc/homeassistant
    state: directory
    mode: '0755'
    owner: homeassistant
    group: homeassistant

- name: Ensure the homeassistant systemd unit file
  template:
    src: templates/homeassistant.service.j2
    dest: /usr/lib/systemd/system/homeassistant.service

- name: Enable the homeassistant daemon
  systemd:
    name: homeassistant.service
    state: started
    enabled: true
    daemon_reload: yes

- name: Ensure Home Assistant port 8123 is open
  firewalld:
    port: 8123/tcp
    permanent: yes
    state: enabled
  notify: reload_firewalld

