---

- name: Include tasks file for authoritative DNS servers"
  include: configure_authoritative_dns.yml
  when: (primary_zones is defined) or (secondary_zones is defined)

- name: "Include tasks file for recursive DNS servers"
  include: configure_recursive_dns.yml
  when: (recursive_dns_server is defined) and (recursive_dns_server == True)

