---
# tasks file for vault
#
- name: Create Vault container
  containers.podman.podman_container:
    name: vault
    image: "docker.io/hashicorp/vault:latest"
    state: started
    #entrypoint: vault server -config /vault/config/vault.hcl
    entrypoint: /bin/vault
    command:
      - server
      - -config
      - /vault/config/vault.hcl
    volume:
      - "/home/containers/vault/config:/vault/config"
      - "/home/containers/vault/file:/vault/file"
    ports:
      - "8200:8200"

- name: Create systemd unit file for Vault container
  containers.podman.podman_generate_systemd:
    name: vault
    new: true
    restart_policy: always
    no_header: true
    dest: /home/containers/.config/systemd/user

- name: Ensure Vault container is started and enabled
  ansible.builtin.systemd:
    name: container-vault
    daemon_reload: true
    state: started
    enabled: true
    scope: user
