---
# tasks file for vault

- name: Add Hasicorp vault repository
  yum_repository:
    name: hashicorpvault
    description: Hasicorp vault repository
    file: hashicorpvault
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: install the latest version Hasicorp Vault
  yum:
    name: vault
    state: latest

- name: Hasicorp vault server configuration file
  template:
    src: templates/vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
  notify: restart_vault

- name: Open firewall port for Hasicorp vault traffic
  firewalld:
    port: 8200/tcp
    permanent: yes
    state: enabled

- name: Start and enable Hasicorp vault daemon
  service:
    name: vault
    state: started
    enabled: yes
