- name: "Ensure OpenSMTPD config"
  template:
    src: templates/smtpd.conf.j2
    dest: /etc/mail/smtpd.conf
  notify: restart_smtpd

- name: "Ensure OpenSMTPD is enabled and started"
  service:
    name: smtpd
    enabled: yes
    state: started

- name: "Ensure Dovecot is installed"
  openbsd_pkg:
    name: dovecot
    state: installed

- name: "Ensure login.conf contains dovecot entry"
  template:
    src: ../templates/login.conf.j2
    dest: /etc/login.conf

- name: "Ensure Dovecot config"
  template:
    src: "templates/{{ item }}"
    dest: "/etc/dovecot/conf.d/{{ item | regex_replace('\\.j2', '') }}"
  notify: restart_dovecot
  loop:
    - 10-ssl.conf.j2
    - 10-mail.conf.j2

- name: "Ensure Dovecot is enabled and started"
  service:
    name: dovecot
    enabled: yes
    state: started
