- name: "Ensure OpenSMTPD config"
  template:
    src: templates/smtpd.conf.j2
    dest: /etc/mail/smtpd.conf
  notify: restart_smtpd

- name: "Ensure OpenSMTPD is enabled and started"
  service:
    name: smtpd
    enabled: yes
    state: started

- name: "Ensure Dovecot is installed"
  openbsd_pkg:
    name: dovecot
    state: installed

- name: "Ensure login.conf contains dovecot entry"
  template:
    src: ../templates/login.conf.j2
    dest: /etc/login.conf

- name: "Ensure Dovecot SSL config"
  template:
    src: templates/10-ssl.conf.j2
    dest: /etc/dovecot/conf.d/10-ssl.conf
  notify: restart_dovecot

- name: "Ensure Dovecot is enabled and started"
  service:
    name: dovecot
    enabled: yes
    state: started
