---

- name: Ensure mail packages are installed
  openbsd_pkg:
    name: ['redis', 'rspamd', 'opensmtpd-filter-rspamd', 'py3-cryptography']
    state: present

- name: Ensure OpenSMTPD config file
  template:
    src: ../templates/smtpd.conf.j2
    dest: /etc/mail/smtpd.conf
  notify:
    - restart_smtpd

- name: Ensure OpenSMTPD is enabled and started
  service:
    name: smtpd
    enabled: True
    state: started

- name: "Ensure OpenDKIM config directory exists"
  file:
    path: /etc/mail/dkim
    state: directory
    mode: '0750'
    owner: _rspamd
    group: _rspamd

- name: "Ensure OpenDKIM keys directory exists"
  file:
    path: /etc/mail/dkim/keys
    state: directory
    mode: '0750'
    owner: _rspamd
    group: _rspamd

- name: "Ensure OpenDKIM keys directories exist"
  file:
    path: "/etc/mail/dkim/keys/{{ item }}"
    state: directory
    mode: '0750'
    owner: _rspamd
    group: _rspamd
  with_items: "{{ mail_domains }}"

- name: "Ensure DKIM private key file"
  openssl_privatekey:
    path: "/etc/mail/dkim/keys/{{ item }}/{{ item }}.key"
    size: 2048
    owner: _rspamd
    group: _rspamd
  with_items: "{{ mail_domains }}"

- name: "Ensure DKIM public key file"
  openssl_publickey:
    path: "/etc/mail/dkim/keys/{{ item }}/{{ item }}.pub"
    privatekey_path: "/etc/mail/dkim/keys/{{ item }}/{{ item }}.key"
    owner: _rspamd
    group: _rspamd
  with_items: "{{ mail_domains }}"

#We need the OpenDKIM public key for the DNS zone file in the DNS role
- name: "Fetch DKIM public key files for DNS role"
  slurp:
    src: "/etc/mail/dkim/keys/{{ item }}/{{ item }}.pub"
  register: dkim_pub_files
  with_items: "{{ mail_domains }}"

- name: Extract DKIM Public key from saved public pey file for DNS role
  set_fact: 
    dkim_pub_keys: "{{ dkim_pub_keys | default([]) + [ { 'mail_server': inventory_hostname_short, 'dkim_domain': item.item, 'dkim_pub_key': item.content | b64decode | regex_replace('^-----BEGIN PUBLIC KEY-----\n', '') | regex_replace('\n-----END PUBLIC KEY-----\n', '') } ] }}"
  with_items: "{{ dkim_pub_files.results }}"

- name: Ensure Rspamd DKIM config file
  template:
    src: ../templates/dkim_signing.conf.j2
    dest: /etc/rspamd/local.d/dkim_signing.conf
  notify: restart_rspamd
  
- name: Ensure rspamd is enabled and started
  service:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - redis
    - rspamd
