- name: "Ensure mail packages are installed"
  openbsd_pkg:
    name: "{{ packages }}"
  vars:
    packages:
      - rspamd-1.9.4
      - postfix-3.5.20200203-sasl2-ldap
      - opendkim-2.10.3p1

- name: "Ensure OpenSMTP is stopped and disabled"
  service:
    name: smtpd
    enabled: False
    state: stopped

- name: "Enasure OpenDKIM config directory exists"
  file:
    path: /etc/opendkim
    state: directory
    owner: _opendkim
    group: _opendkim
    mode: '0750'

- name: "Ensure OpenDKIM keys directories exist"
  file:
    path: "/etc/opendkim/keys/{{ item }}"
    state: directory
    owner: _opendkim
    group: _opendkim
    mode: '0750'
  with_items: "{{ mail_domains }}"

- name: "Ensure OpenDKIM keys exist"
  command: "/usr/local/sbin/opendkim-genkey -s {{ ansible_hostname }} -d {{ item }}"
  args:
    chdir: /etc/opendkim/keys/{{ item }}/
    creates: /etc/opendkim/keys/{{ item }}/{{ ansible_hostname }}.private
  with_items: "{{ mail_domains }}"

#We need the OpenDKIM public key for the DNS zone file in the dns role
- name: "Ensure OpenDKIM keys are available for DNS role"
  slurp:
    src: "/etc/opendkim/keys/{{ item }}/{{ ansible_hostname }}.txt"
  register: opendkim_keys
  with_items: "{{ mail_domains }}"

#opendkim-genkey Runs as root so we must chown to _opendkim for OpenDKIM to work
- name: "Ensure OpenDKIM keys are owned by _opendkim"
  file:
    path: /etc/opendkim/keys
    state: directory
    recurse: yes
    owner: _opendkim
    group: _opendkim

- name: "Ensure OpenDKIM main config file"
  template:
    src: templates/opendkim.conf.j2
    dest: /etc/opendkim.conf
    owner: _opendkim
    group: _opendkim
    mode: 0640
  notify: restart_opendkim

- name: "Ensure OpenDKIM KeyTable config file"
  template:
    src: templates/KeyTable.j2
    dest: /etc/opendkim/KeyTable
    owner: _opendkim
    group: _opendkim
    mode: 0640
  notify: restart_opendkim

- name: "Ensure OpenDKIM SigningTable config file"
  template:
    src: templates/SigningTable.j2
    dest: /etc/opendkim/SigningTable
    owner: _opendkim
    group: _opendkim
    mode: 0640
  notify: restart_opendkim

- name: "Ensure OpenDKIM TrustedHosts config file"
  template:
    src: templates/TrustedHosts.j2
    dest: /etc/opendkim/TrustedHosts
    owner: _opendkim
    group: _opendkim
    mode: 0640
  notify: restart_opendkim


- name: "Ensure OpenDKIM is enabled and started"
  service:
    name: opendkim
    enabled: yes
    state: started

- name: "Ensure Rspamd is enabled and started"
  service:
    name: rspamd
    enabled: yes
    state: started

- name: "Ensure Postfix transport table"
  template:
    src: templates/transport.j2
    dest: /etc/postfix/transport
  notify: 
    - update_transport_table
    - restart_postfix

- name: "Ensure Postfix aliases table"
  template:
    src: templates/aliases.j2
    dest: /etc/postfix/aliases
  notify: 
    - update_aliases_table
    - restart_postfix

- name: "Ensure Postfix config"
  template:
    src: templates/main.cf.j2
    dest: /etc/postfix/main.cf
  notify: restart_postfix

- name: "Ensure Postfix is enabled and started"
  service:
    name: postfix
    enabled: yes
    state: started
