---
# tasks file for website

- name: "Ensure gtar (gnu tar) is installed"
  openbsd_pkg:
    name: gtar-1.34-static
    state: present

- name: "Ensure the website's main directry exists"
  file:
    path: /var/www/htdocs/{{ item }}
    state: directory
    mode: '0755'
  with_items:
    - www.derksencomputing.nl

- name: "Ensure the website's files are deployed"
  unarchive:
    src: "files/{{ item }}.tar.gz"
    dest: /var/www/htdocs
    owner: root
    group: daemon
  with_items:
    - www.derksencomputing.nl

- name: "Ensure httpd configuration file"
  template:
    src: templates/httpd.conf.j2
    dest: /etc/httpd.conf
  notify: restart_httpd

- name: "Ensure httpd daemon is enabled and started"
  service:
    name: httpd
    state: started
    enabled: true
