---
# handlers file for monitoring

- name: restart_prometheus
  service:
    state: restarted
    name: prometheus

- name: restart_alertmanager
  service:
    state: restarted
    name: alertmanager

- name: reload_firewalld
  service:
    state: restarted
    name: firewalld
