---
# handlers file for mail

- name: restart_dovecot
  listen: x509_certificate_event
  service:
    name: dovecot
    state: restarted

- name: restart_opendkim
  listen: x509_certificate_event
  service:
    name: opendkim
    state: restarted

- name: reload_firewalld
  command: /usr/bin/firewall-cmd --reload

- name: restart_smtpd
  listen: x509_certificate_event
  service:
    name: smtpd
    state: restarted

- name: restart_rspamd
  listen: x509_certificate_event
  service:
    name: rspamd
    state: restarted
